-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-22 13:48:20 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Addresses 
    ( 
     Address_ID        SERIAL8  NOT NULL , 
     City              VARCHAR (100)  NOT NULL , 
     Postcode          VARCHAR (10)  NOT NULL , 
     Street            VARCHAR (200)  NOT NULL , 
     State             VARCHAR (100)  NOT NULL , 
     Clients_Client_ID SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Addresses 
    ADD CONSTRAINT Addresses_PK PRIMARY KEY ( Address_ID, Clients_Client_ID ) ;

CREATE TABLE Administrators 
    ( 
     Administrator_ID SERIAL4  NOT NULL , 
     First_name       VARCHAR (50)  NOT NULL , 
     Last_name        VARCHAR (100)  NOT NULL , 
     Login            VARCHAR (50)  NOT NULL , 
     Password         VARCHAR (256)  NOT NULL , 
     Email            VARCHAR (254)  NOT NULL , 
     Phone            VARCHAR (20) , 
     Create_date      TIMESTAMPTZ  NOT NULL ,
     Modify_date      TIMESTAMPTZ  NOT NULL , 
     Last_login       TIMESTAMPTZ  NOT NULL 
    ) 
;

ALTER TABLE Administrators 
    ADD CONSTRAINT Administrators_PK PRIMARY KEY ( Administrator_ID ) ;

CREATE TABLE Carts 
    ( 
     Quantity            SMALLINT  NOT NULL , 
     Price               DECIMAL (7,2)  NOT NULL , 
     Add_date            TIMESTAMPTZ  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL , 
     Clients_Client_ID   SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Carts 
    ADD CONSTRAINT Carts_PK PRIMARY KEY ( Clients_Client_ID, Products_Product_ID, Quantity ) ;

CREATE TABLE Clients 
    ( 
     Client_ID  SERIAL8  NOT NULL , 
     First_name VARCHAR (50)  NOT NULL , 
     Last_name  VARCHAR (100)  NOT NULL , 
     Login      VARCHAR (50)  NOT NULL , 
     Password   VARCHAR (256)  NOT NULL , 
     Email      VARCHAR (254)  NOT NULL , 
     Phone      VARCHAR (20) , 
     Status     BOOLEAN  NOT NULL , 
     Newsletter BOOLEAN , 
     Last_login TIMESTAMPTZ  NOT NULL , 
     Join_date  TIMESTAMPTZ  NOT NULL , 
     Birthdate  TIMESTAMPTZ,
     Create_date TIMESTAMPTZ,
     Modify_date TIMESTAMPTZ
    ) 
;

ALTER TABLE Clients 
    ADD CONSTRAINT Clients_PK PRIMARY KEY ( Client_ID ) ;

CREATE TABLE Delivery_dictionary 
    ( 
     Delivery_dict_ID SERIAL2  NOT NULL , 
     Name             VARCHAR (64)  NOT NULL , 
     Price            DECIMAL (5,2)  NOT NULL 
    ) 
;

ALTER TABLE Delivery_dictionary 
    ADD CONSTRAINT Delivery_dictionary_PK PRIMARY KEY ( Delivery_dict_ID ) ;

CREATE TABLE Medias 
    ( 
     Media_ID    SERIAL4  NOT NULL , 
     Name        VARCHAR (128)  NOT NULL , 
     Path        VARCHAR (256)  NOT NULL , 
     Create_date TIMESTAMPTZ  NOT NULL,
     Modify_date TIMESTAMPTZ  NOT NULL 
    ) 
;

ALTER TABLE Medias 
    ADD CONSTRAINT Medias_PK PRIMARY KEY ( Media_ID ) ;

CREATE TABLE Navigation 
    ( 
     Navigation_ID                   SERIAL4  NOT NULL , 
     Name                            VARCHAR (30)  NOT NULL , 
     Url                             VARCHAR (512)  NOT NULL , 
     Position                        INTEGER  NOT NULL , 
     Status                          BOOLEAN  NOT NULL ,
     Create_date                     TIMESTAMPTZ  NOT NULL , 
     Modify_date                     TIMESTAMPTZ  NOT NULL ,  
     Navigation_Navigation_ID        INTEGER , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_PK PRIMARY KEY ( Navigation_ID ) ;

CREATE TABLE Ordered_products 
    ( 
     Quantity            SMALLINT  NOT NULL , 
     Total_price         DECIMAL (7,2)  NOT NULL , 
     VAT_percentage      SMALLINT  NOT NULL , 
     Orders_Order_ID     SERIAL8  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL 
    ) 
;

CREATE TABLE Orders 
    ( 
     Order_ID          SERIAL8  NOT NULL , 
     Status            BOOLEAN  NOT NULL , 
     Payment_name      VARCHAR (64)  NOT NULL , 
     Payment_price     DECIMAL (5,2)  NOT NULL , 
     Delivery_name     VARCHAR (64)  NOT NULL , 
     Delivery_price    DECIMAL (5,2)  NOT NULL , 
     Order_note        VARCHAR (500) , 
     Address_city      VARCHAR (100)  NOT NULL , 
     Address_postcode  VARCHAR (10)  NOT NULL , 
     Address_street    VARCHAR (200)  NOT NULL , 
     Address_state     VARCHAR (100)  NOT NULL , 
     Total_price       DECIMAL (7,2)  NOT NULL , 
     Clients_Client_ID SERIAL8  NOT NULL,
     Create_date TIMESTAMPTZ NOT NULL,
     Modify_date TIMESTAMPTZ NOT NULL
    ) 
;

ALTER TABLE Orders 
    ADD CONSTRAINT Orders_PK PRIMARY KEY ( Order_ID ) ;

CREATE TABLE Pages 
    ( 
     Page_ID                         SERIAL4  NOT NULL , 
     Name                            VARCHAR (50)  NOT NULL , 
     Type                            VARCHAR (50)  NOT NULL , 
     Content                         TEXT  NOT NULL , 
     Create_date                     TIMESTAMPTZ  NOT NULL , 
     Modify_date                     TIMESTAMPTZ  NOT NULL , 
     Status                          BOOLEAN  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Pages 
    ADD CONSTRAINT Pages_PK PRIMARY KEY ( Page_ID ) ;

CREATE TABLE Pages_medias 
    ( 
     Medias_Media_ID SERIAL4  NOT NULL , 
     Pages_Page_ID   SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_PK PRIMARY KEY ( Medias_Media_ID, Pages_Page_ID ) ;

CREATE TABLE Payment_dictionary 
    ( 
     Payment_dict_ID SERIAL2  NOT NULL , 
     Name            VARCHAR (64)  NOT NULL , 
     Price           DECIMAL (5,2)  NOT NULL 
    ) 
;

ALTER TABLE Payment_dictionary 
    ADD CONSTRAINT Payment_dictionary_PK PRIMARY KEY ( Payment_dict_ID ) ;

CREATE TABLE Product_category_dictionary 
    ( 
     Product_dict_ID SERIAL4  NOT NULL , 
     Name            VARCHAR (64)  NOT NULL 
    ) 
;

ALTER TABLE Product_category_dictionary 
    ADD CONSTRAINT Product_category_dictionary_PK PRIMARY KEY ( Product_dict_ID ) ;

CREATE TABLE Product_metadata 
    ( 
     Product_metadata_ID SERIAL4  NOT NULL , 
     Key                 VARCHAR (128)  NOT NULL , 
     Value               VARCHAR (128)  NOT NULL 
    ) 
;

ALTER TABLE Product_metadata 
    ADD CONSTRAINT Product_metadata_PK PRIMARY KEY ( Product_metadata_ID ) ;

CREATE TABLE Products 
    ( 
     Product_ID                           SERIAL4  NOT NULL , 
     Name                                 VARCHAR (128)  NOT NULL , 
     Create_date                          TIMESTAMPTZ  NOT NULL , 
     Is_animal                            BOOLEAN  NOT NULL , 
     Price                                DECIMAL (6,2)  NOT NULL , 
     Availability                         BOOLEAN  NOT NULL , 
     VAT_percentage                       INTEGER  NOT NULL , 
     Product_code                         VARCHAR (6)  NOT NULL , 
     Description                          TEXT  NOT NULL , 
     Product_category                     VARCHAR (64)  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Product_metadata_Product_metadata_ID INTEGER,
     Modify_date                          TIMESTAMPTZ  NOT NULL
    ) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( Product_ID ) ;

CREATE TABLE Products_medias 
    ( 
     Products_Product_ID SERIAL4  NOT NULL , 
     Medias_Media_ID     SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_PK PRIMARY KEY ( Products_Product_ID, Medias_Media_ID ) ;

CREATE TABLE Reviews 
    ( 
     Review_ID           SERIAL8  NOT NULL , 
     Content             TEXT  NOT NULL , 
     Grade               SMALLINT  NOT NULL , 
     Create_date         TIMESTAMPTZ  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL , 
     Clients_Client_ID   SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_PK PRIMARY KEY ( Review_ID, Clients_Client_ID, Products_Product_ID ) ;

CREATE TABLE Settings 
    ( 
     Settings_ID                     SERIAL4  NOT NULL , 
     Name                            VARCHAR (128)  NOT NULL , 
     Value                           VARCHAR (128)  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID SERIAL4 
    ) 
;

ALTER TABLE Settings 
    ADD CONSTRAINT Settings_PK PRIMARY KEY ( Settings_ID ) ;

CREATE TABLE VAT_Percentage_dictionary 
    ( 
     VAT_percentage_dict_ID SERIAL2  NOT NULL , 
     Percentage             SMALLINT  NOT NULL 
    ) 
;

ALTER TABLE VAT_Percentage_dictionary 
    ADD CONSTRAINT VAT_Percentage_dictionary_PK PRIMARY KEY ( VAT_percentage_dict_ID ) ;

ALTER TABLE Addresses 
    ADD CONSTRAINT Addresses_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_Navigation_FK FOREIGN KEY 
    ( 
     Navigation_Navigation_ID
    ) 
    REFERENCES Navigation 
    ( 
     Navigation_ID
    ) 
;

ALTER TABLE Ordered_products 
    ADD CONSTRAINT Ordered_products_Orders_FK FOREIGN KEY 
    ( 
     Orders_Order_ID
    ) 
    REFERENCES Orders 
    ( 
     Order_ID
    ) 
;

ALTER TABLE Ordered_products 
    ADD CONSTRAINT Ordered_products_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Orders 
    ADD CONSTRAINT Orders_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Pages 
    ADD CONSTRAINT Pages_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_Medias_FK FOREIGN KEY 
    ( 
     Medias_Media_ID
    ) 
    REFERENCES Medias 
    ( 
     Media_ID
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_Pages_FK FOREIGN KEY 
    ( 
     Pages_Page_ID
    ) 
    REFERENCES Pages 
    ( 
     Page_ID
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_Medias_FK FOREIGN KEY 
    ( 
     Medias_Media_ID
    ) 
    REFERENCES Medias 
    ( 
     Media_ID
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Settings 
    ADD CONSTRAINT Settings_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             1
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   4
-- WARNINGS                                 0





-- ADMINISTRATORS password: admin123

INSERT INTO administrators (first_name, last_name, login, password, email, phone, create_date, modify_date, last_login) VALUES ('a', 'b', 'c', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'a@b.c', 123456789, '10-10-2025', '10-10-2025', '10-10-2025');

-- NAVIGATION

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Home', '/shop/main', 10, true, '10-10-2025', '10-10-2025', null, 1);
    
INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Products', '/search/products', 20, true, '10-10-2025', '10-10-2025', null, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Search', '/search/products', 30, true, '10-10-2025', '10-10-2025', null, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Product', '/products/1', 40, true, '10-10-2025', '10-10-2025', 3, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Checkout', '/checkout', 50, true, '10-10-2025', '10-10-2025', null, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Contact', '/page/contact', 60, true, '10-10-2025', '10-10-2025', null, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('Cart', '/cart', 70, true, '10-10-2025', '10-10-2025', null, 1);

INSERT INTO navigation (name, url, position, status, create_date, modify_date, navigation_navigation_id, administrators_administrator_id)
    VALUES ('About', '/page/about', 80, true, '10-10-2025', '10-10-2025', null, 1);


-- PAGES

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('main', 'shop', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('cart', 'cart', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('checkout', 'checkout', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('products', 'products', '{"Availability":true,"ShowType":true,"AllowQuantity":true,"ShowRelated":false,"ShowReviews":false}', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('contact', 'page', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('about', 'page', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('search', 'search', '', '10-10-2025', '10-10-2025', true, 1);

INSERT INTO pages (name, type, content, create_date, modify_date, status, administrators_administrator_id)
    VALUES ('profile', 'profile', '', '10-10-2025', '10-10-2025', true, 1);


-- PAYMENT DICTIONARY

INSERT INTO payment_dictionary (name, price) VALUES ('Blik', 5.50);
INSERT INTO payment_dictionary (name, price) VALUES ('Visa', 1.00);
INSERT INTO payment_dictionary (name, price) VALUES ('Personal', 0.00);


-- PRODUCT CATEGORY DICTIONARY

INSERT INTO product_category_dictionary (name) VALUES ('Żabeczki');
INSERT INTO product_category_dictionary (name) VALUES ('Terrarium');
INSERT INTO product_category_dictionary (name) VALUES ('Kotki');
INSERT INTO product_category_dictionary (name) VALUES ('Salamandry');

-- VAT PERCENTAGE DICTIONARY

INSERT INTO vat_percentage_dictionary (percentage) VALUES (12);
INSERT INTO vat_percentage_dictionary (percentage) VALUES (27);

-- DELIVERY DICTIONARY

INSERT INTO delivery_dictionary (name, price) VALUES ('Personal', 0.00);
INSERT INTO delivery_dictionary (name, price) VALUES ('DHL', 14.89);
INSERT INTO delivery_dictionary (name, price) VALUES ('Inpost', 19.99);

-- PRODUCTS (EXAMPLE)

INSERT INTO products (name, create_date, is_animal, price, availability, vat_percentage, product_code, description, product_category, product_metadata_product_metadata_id, modify_date)
    VALUES ('Żaba', '10-10-2025', true, 49.99, true, 12, 'ZB123', 'Little distinguish man', 'Żabeczki', null, '10-10-2025');

INSERT INTO products (name, create_date, is_animal, price, availability, vat_percentage, product_code, description, product_category, product_metadata_product_metadata_id, modify_date)
    VALUES ('Terrarium', '10-10-2025', false, 199.43, true, 12, 'TR123', 'Cool thingy for your froggies', 'Terrarium', null, '10-10-2025');

INSERT INTO products (name, create_date, is_animal, price, availability, vat_percentage, product_code, description, product_category, product_metadata_product_metadata_id, modify_date)
    VALUES ('A cat', '10-10-2025', true, 999, true, 27, 'CT123', 'Little distinguish man as well', 'Kotki', null, '10-10-2025');

INSERT INTO products (name, create_date, is_animal, price, availability, vat_percentage, product_code, description, product_category, product_metadata_product_metadata_id, modify_date)
    VALUES ('Salamandra bezplamista', '10-10-2025', true, 21.37, true, 12, 'ZB123', 'He tries his best', 'Salamandry', null, '10-10-2025');


-- MEDIAS

INSERT INTO medias (name, path, create_date, modify_date) VALUES ('frog.jpg', '../media/products/main/frog.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('frog.jpg', '../media/products/icons/frog.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('terrarium.jpg', '../media/products/main/terrarium.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('terrarium.jpg', '../media/products/icons/terrarium.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('cat.jpg', '../media/products/main/cat.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('cat.png', '../media/products/icons/cat.png', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('salamandra.jpg', '../media/products/main/salamandra.jpg', '10-10-2025', '10-10-2025');
INSERT INTO medias (name, path, create_date, modify_date) VALUES ('salamandra.jpg', '../media/products/icons/salamandra.jpg', '10-10-2025', '10-10-2025');


-- PRODUCT_MEDIAS

INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (1, 1);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (1, 2);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (2, 3);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (2, 4);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (3, 5);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (3, 6);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (4, 7);
INSERT INTO products_medias (products_product_id, medias_media_id) VALUES (4, 8);


-- CLIENTS

INSERT INTO clients (first_name, last_name, login, password, email, phone, status, newsletter, last_login, join_date, birthdate, create_date, modify_date)
    VALUES ('Barry', 'Benson', 'Bee', '65e84be33532fb784c48129675f9eff3a682b27168c0ea744b2cf58ee02337c5', 'a@b.c', null, false, false, '10-10-2025', '10-10-2025', null, '10-10-2025', '10-10-2025')
