-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-22 13:48:20 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Addresses 
    ( 
     Address_ID        SERIAL8  NOT NULL , 
     City              VARCHAR (100)  NOT NULL , 
     Postcode          VARCHAR (10)  NOT NULL , 
     Street            VARCHAR (200)  NOT NULL , 
     State             VARCHAR (100)  NOT NULL , 
     Clients_Client_ID SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Addresses 
    ADD CONSTRAINT Addresses_PK PRIMARY KEY ( Address_ID, Clients_Client_ID ) ;

CREATE TABLE Administrators 
    ( 
     Administrator_ID SERIAL4  NOT NULL , 
     First_name       VARCHAR (50)  NOT NULL , 
     Last_name        VARCHAR (100)  NOT NULL , 
     Login            VARCHAR (50)  NOT NULL , 
     Password         VARCHAR (256)  NOT NULL , 
     Email            VARCHAR (254)  NOT NULL , 
     Phone            VARCHAR (20) , 
     Create_date      TIMESTAMPTZ  NOT NULL ,
     Modify_date      TIMESTAMPTZ  NOT NULL , 
     Last_login       TIMESTAMPTZ  NOT NULL 
    ) 
;

ALTER TABLE Administrators 
    ADD CONSTRAINT Administrators_PK PRIMARY KEY ( Administrator_ID ) ;

CREATE TABLE Carts 
    ( 
     Quantity            SMALLINT  NOT NULL , 
     Price               DECIMAL (7,2)  NOT NULL , 
     Add_date            TIMESTAMPTZ  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL , 
     Clients_Client_ID   SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Carts 
    ADD CONSTRAINT Carts_PK PRIMARY KEY ( Clients_Client_ID, Products_Product_ID, Quantity ) ;

CREATE TABLE Clients 
    ( 
     Client_ID  SERIAL8  NOT NULL , 
     First_name VARCHAR (50)  NOT NULL , 
     Last_name  VARCHAR (100)  NOT NULL , 
     Login      VARCHAR (50)  NOT NULL , 
     Password   VARCHAR (256)  NOT NULL , 
     Email      VARCHAR (254)  NOT NULL , 
     Phone      VARCHAR (20) , 
     Status     BOOLEAN  NOT NULL , 
     Newsletter BOOLEAN , 
     Last_login TIMESTAMPTZ  NOT NULL , 
     Join_date  TIMESTAMPTZ  NOT NULL , 
     Birthdate  TIMESTAMPTZ 
    ) 
;

ALTER TABLE Clients 
    ADD CONSTRAINT Clients_PK PRIMARY KEY ( Client_ID ) ;

CREATE TABLE Delivery_dictionary 
    ( 
     Delivery_dict_ID SERIAL2  NOT NULL , 
     Name             VARCHAR (64)  NOT NULL , 
     Price            DECIMAL (5,2)  NOT NULL 
    ) 
;

ALTER TABLE Delivery_dictionary 
    ADD CONSTRAINT Delivery_dictionary_PK PRIMARY KEY ( Delivery_dict_ID ) ;

CREATE TABLE Medias 
    ( 
     Media_ID    SERIAL4  NOT NULL , 
     Name        VARCHAR (128)  NOT NULL , 
     Path        VARCHAR (256)  NOT NULL , 
     Upload_date TIMESTAMPTZ  NOT NULL 
    ) 
;

ALTER TABLE Medias 
    ADD CONSTRAINT Medias_PK PRIMARY KEY ( Media_ID ) ;

CREATE TABLE Navigation 
    ( 
     Navigation_ID                   SERIAL4  NOT NULL , 
     Name                            VARCHAR (30)  NOT NULL , 
     Url                             VARCHAR (512)  NOT NULL , 
     Position                        INTEGER  NOT NULL , 
     Status                          BOOLEAN  NOT NULL ,
     Create_date                     TIMESTAMPTZ  NOT NULL , 
     Modify_date                     TIMESTAMPTZ  NOT NULL ,  
     Navigation_Navigation_ID        INTEGER , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_PK PRIMARY KEY ( Navigation_ID ) ;

CREATE TABLE Ordered_products 
    ( 
     Quantity            SMALLINT  NOT NULL , 
     Total_price         DECIMAL (7,2)  NOT NULL , 
     VAT_percentage      SMALLINT  NOT NULL , 
     Orders_Order_ID     SERIAL8  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL 
    ) 
;

CREATE TABLE Orders 
    ( 
     Order_ID          SERIAL8  NOT NULL , 
     Status            BOOLEAN  NOT NULL , 
     Payment_name      VARCHAR (64)  NOT NULL , 
     Payment_price     DECIMAL (5,2)  NOT NULL , 
     Delivery_name     VARCHAR (64)  NOT NULL , 
     Delivery_price    DECIMAL (5,2)  NOT NULL , 
     Order_note        VARCHAR (500) , 
     Address_city      VARCHAR (100)  NOT NULL , 
     Address_postcode  VARCHAR (10)  NOT NULL , 
     Address_street    VARCHAR (200)  NOT NULL , 
     Address_state     VARCHAR (100)  NOT NULL , 
     Total_price       DECIMAL (7,2)  NOT NULL , 
     Clients_Client_ID SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Orders 
    ADD CONSTRAINT Orders_PK PRIMARY KEY ( Order_ID ) ;

CREATE TABLE Pages 
    ( 
     Page_ID                         SERIAL4  NOT NULL , 
     Name                            VARCHAR (50)  NOT NULL , 
     Type                            VARCHAR (50)  NOT NULL , 
     Content                         TEXT  NOT NULL , 
     Create_date                     TIMESTAMPTZ  NOT NULL , 
     Modify_date                     TIMESTAMPTZ  NOT NULL , 
     Status                          BOOLEAN  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Pages 
    ADD CONSTRAINT Pages_PK PRIMARY KEY ( Page_ID ) ;

CREATE TABLE Pages_medias 
    ( 
     Medias_Media_ID SERIAL4  NOT NULL , 
     Pages_Page_ID   SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_PK PRIMARY KEY ( Medias_Media_ID, Pages_Page_ID ) ;

CREATE TABLE Payment_dictionary 
    ( 
     Payment_dict_ID SERIAL2  NOT NULL , 
     Name            VARCHAR (64)  NOT NULL , 
     Price           DECIMAL (5,2)  NOT NULL 
    ) 
;

ALTER TABLE Payment_dictionary 
    ADD CONSTRAINT Payment_dictionary_PK PRIMARY KEY ( Payment_dict_ID ) ;

CREATE TABLE Product_category_dictionary 
    ( 
     Product_dict_ID SERIAL4  NOT NULL , 
     Name            VARCHAR (64)  NOT NULL 
    ) 
;

ALTER TABLE Product_category_dictionary 
    ADD CONSTRAINT Product_category_dictionary_PK PRIMARY KEY ( Product_dict_ID ) ;

CREATE TABLE Product_metadata 
    ( 
     Product_metadata_ID SERIAL4  NOT NULL , 
     Key                 VARCHAR (128)  NOT NULL , 
     Value               VARCHAR (128)  NOT NULL 
    ) 
;

ALTER TABLE Product_metadata 
    ADD CONSTRAINT Product_metadata_PK PRIMARY KEY ( Product_metadata_ID ) ;

CREATE TABLE Products 
    ( 
     Product_ID                           SERIAL4  NOT NULL , 
     Name                                 VARCHAR (128)  NOT NULL , 
     Create_date                          TIMESTAMPTZ  NOT NULL , 
     Is_animal                            BOOLEAN  NOT NULL , 
     Price                                DECIMAL (6,2)  NOT NULL , 
     Availability                         BOOLEAN  NOT NULL , 
     VAT_percentage                       INTEGER  NOT NULL , 
     Product_code                         VARCHAR (6)  NOT NULL , 
     Description                          TEXT  NOT NULL , 
     Product_category                     VARCHAR (64)  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Product_metadata_Product_metadata_ID SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Products 
    ADD CONSTRAINT Products_PK PRIMARY KEY ( Product_ID ) ;

CREATE TABLE Products_medias 
    ( 
     Products_Product_ID SERIAL4  NOT NULL , 
     Medias_Media_ID     SERIAL4  NOT NULL 
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_PK PRIMARY KEY ( Products_Product_ID, Medias_Media_ID ) ;

CREATE TABLE Reviews 
    ( 
     Review_ID           SERIAL8  NOT NULL , 
     Content             TEXT  NOT NULL , 
     Grade               SMALLINT  NOT NULL , 
     Create_date         TIMESTAMPTZ  NOT NULL , 
     Products_Product_ID SERIAL4  NOT NULL , 
     Clients_Client_ID   SERIAL8  NOT NULL 
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_PK PRIMARY KEY ( Review_ID, Clients_Client_ID, Products_Product_ID ) ;

CREATE TABLE Settings 
    ( 
     Settings_ID                     SERIAL4  NOT NULL , 
     Name                            VARCHAR (128)  NOT NULL , 
     Value                           VARCHAR (128)  NOT NULL , 
--  ERROR: Column name length exceeds maximum allowed length(30) 
     Administrators_Administrator_ID SERIAL4 
    ) 
;

ALTER TABLE Settings 
    ADD CONSTRAINT Settings_PK PRIMARY KEY ( Settings_ID ) ;

CREATE TABLE VAT_Percentage_dictionary 
    ( 
     VAT_percentage_dict_ID SERIAL2  NOT NULL , 
     Percentage             SMALLINT  NOT NULL 
    ) 
;

ALTER TABLE VAT_Percentage_dictionary 
    ADD CONSTRAINT VAT_Percentage_dictionary_PK PRIMARY KEY ( VAT_percentage_dict_ID ) ;

ALTER TABLE Addresses 
    ADD CONSTRAINT Addresses_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;

ALTER TABLE Navigation 
    ADD CONSTRAINT Navigation_Navigation_FK FOREIGN KEY 
    ( 
     Navigation_Navigation_ID
    ) 
    REFERENCES Navigation 
    ( 
     Navigation_ID
    ) 
;

ALTER TABLE Ordered_products 
    ADD CONSTRAINT Ordered_products_Orders_FK FOREIGN KEY 
    ( 
     Orders_Order_ID
    ) 
    REFERENCES Orders 
    ( 
     Order_ID
    ) 
;

ALTER TABLE Ordered_products 
    ADD CONSTRAINT Ordered_products_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Orders 
    ADD CONSTRAINT Orders_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Pages 
    ADD CONSTRAINT Pages_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_Medias_FK FOREIGN KEY 
    ( 
     Medias_Media_ID
    ) 
    REFERENCES Medias 
    ( 
     Media_ID
    ) 
;

ALTER TABLE Pages_medias 
    ADD CONSTRAINT Relation_17_Pages_FK FOREIGN KEY 
    ( 
     Pages_Page_ID
    ) 
    REFERENCES Pages 
    ( 
     Page_ID
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_Medias_FK FOREIGN KEY 
    ( 
     Medias_Media_ID
    ) 
    REFERENCES Medias 
    ( 
     Media_ID
    ) 
;

ALTER TABLE Products_medias 
    ADD CONSTRAINT Relation_18_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Clients_FK FOREIGN KEY 
    ( 
     Clients_Client_ID
    ) 
    REFERENCES Clients 
    ( 
     Client_ID
    ) 
;

ALTER TABLE Reviews 
    ADD CONSTRAINT Reviews_Products_FK FOREIGN KEY 
    ( 
     Products_Product_ID
    ) 
    REFERENCES Products 
    ( 
     Product_ID
    ) 
;

ALTER TABLE Settings 
    ADD CONSTRAINT Settings_Administrators_FK FOREIGN KEY 
    ( 
     Administrators_Administrator_ID
    ) 
    REFERENCES Administrators 
    ( 
     Administrator_ID
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             1
-- ALTER TABLE                             36
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   4
-- WARNINGS                                 0
